import Fastify from 'fastify';
import compress from '@fastify/compress';
import helmet from '@fastify/helmet';
import { registerAdmissionsRoutes } from './admissions-routes';

const app = Fastify({
  logger: {
    level: process.env.LOG_LEVEL || 'info',
    redact: ['req.headers.authorization', 'req.headers.cookie', 'res.headers.set-cookie', 'req.headers.x-enrollment-admin-key']
  },
  trustProxy: true,
  bodyLimit: 1024 * 1024
});

await app.register(compress, { global: true });
await app.register(helmet, {
  global: true,
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"], baseUri: ["'self'"], formAction: ["'self'"], frameAncestors: ["'none'"],
      imgSrc: ["'self'", 'data:'], scriptSrc: ["'self'", "'unsafe-inline'"], styleSrc: ["'self'", "'unsafe-inline'"]
    }
  },
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
  strictTransportSecurity: process.env.RTPU_DEPLOY_ENV === 'production'
    ? { maxAge: 63_072_000, includeSubDomains: true, preload: true }
    : false
});

app.addHook('onSend', async (request, reply, payload) => {
  if (request.url.startsWith('/api/')) reply.header('cache-control', 'no-store, max-age=0');
  return payload;
});

await registerAdmissionsRoutes(app);

const css = `
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111827;background:#f7f2e8}*{box-sizing:border-box}body{margin:0;background:#f7f2e8}.shell{min-height:100vh;padding:28px 16px 60px}.wrap{max-width:1180px;margin:auto}.hero{background:#0b1f3a;color:#fff;border:1px solid #c9a227;border-radius:22px;padding:28px}.hero .eyebrow{color:#d4af37;text-transform:uppercase;letter-spacing:1.4px;font-size:12px;font-weight:900}.hero h1{margin:8px 0;font-size:clamp(30px,5vw,42px)}.hero p{color:#e5e7eb;line-height:1.6;max-width:980px}.nav{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.nav a{background:#fff;border:1px solid #d8d2c4;border-radius:999px;padding:9px 13px;text-decoration:none;font-weight:800;color:#0b1f3a}.panel{background:#fff;border:1px solid #d8d2c4;border-radius:18px;padding:20px;margin:18px 0;box-shadow:0 8px 22px rgba(15,23,42,.045)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.field{display:flex;flex-direction:column;gap:6px}.field label{font-size:13px;font-weight:800;color:#0b1f3a}.field input,.field select,.field textarea{font:inherit;border:1px solid #cbd5e1;border-radius:10px;padding:11px;background:#fff}.field textarea{resize:vertical}.checks{display:grid;gap:10px;margin-top:12px}.checks label{display:flex;gap:9px;align-items:flex-start;line-height:1.45}.button{appearance:none;border:0;border-radius:10px;background:#0b1f3a;color:#fff;font-weight:850;padding:12px 16px;cursor:pointer}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.notice{padding:14px;border-radius:12px;background:#fff8df;border:1px solid #e3c565;line-height:1.5;margin:14px 0}.notice.error{background:#fff1f2;border-color:#fecdd3;color:#881337}.notice.success{background:#ecfdf5;border-color:#86efac;color:#14532d}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;word-break:break-word;white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:14px;border-radius:10px;max-height:520px;overflow:auto}.status{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.metric{border:1px solid #d8d2c4;border-radius:14px;padding:14px;background:#fbfaf6}.metric strong{display:block;color:#0b1f3a;font-size:18px}.muted{color:#6b7280;font-size:13px}.danger{color:#881337;font-weight:800}.section-title{margin-top:28px;color:#0b1f3a;border-bottom:1px solid #e5e7eb;padding-bottom:7px}@media(max-width:640px){.shell{padding:16px 10px 40px}.hero{padding:22px}.panel{padding:16px}}
`;

function layout(title: string, body: string, script = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${title}</title><style>${css}</style></head><body><main class="shell"><section class="wrap"><header class="hero"><div class="eyebrow">Ross Tax Pro University • Admissions & Clearance</div><h1>${title}</h1><p>Institution-standardized intake for admission clearance, references, employment history, prior education, transcript review, FAFSA status tracking, PTIN review, and background-screening authorization.</p></header><nav class="nav"><a href="/">Admissions Control Center</a><a href="https://rtpu-enrollment.onrender.com/">Enrollment Service</a></nav>${body}</section></main>${script ? `<script>${script}</script>` : ''}</body></html>`;
}

const script = `
const q=s=>document.querySelector(s), v=id=>q('#'+id)?.value?.trim?.()||'', c=id=>q('#'+id)?.checked===true;
function arr(csv){return csv.split(',').map(x=>x.trim()).filter(Boolean)}
async function load(){const [seed,bg]=await Promise.all([fetch('/api/admissions/seed').then(r=>r.json()),fetch('/api/admissions/background-policy').then(r=>r.json())]);q('#seed').textContent=JSON.stringify(seed,null,2);q('#bg-status').innerHTML='<div class="metric"><strong>'+(bg.readiness.authorizationFormReady?'READY':'NO')+'</strong><span>authorization form</span></div><div class="metric"><strong>'+(bg.readiness.actualConsumerReportingAgencyConnected?'CONNECTED':'NOT CONNECTED')+'</strong><span>consumer-report provider</span></div><div class="metric"><strong>'+(bg.readiness.liveFederalStateCountySearchExecuted?'EXECUTED':'NOT EXECUTED')+'</strong><span>live record search</span></div>'}
function ref(n){const name=v('ref'+n+'Name');if(!name)return null;return{name,relationship:v('ref'+n+'Relationship'),email:v('ref'+n+'Email'),phone:v('ref'+n+'Phone'),organization:v('ref'+n+'Org'),permissionToContact:c('ref'+n+'Consent')}}
function emp(n){const employer=v('emp'+n+'Employer');if(!employer)return null;return{employer,role:v('emp'+n+'Role'),startDate:v('emp'+n+'Start'),endDate:v('emp'+n+'End'),supervisorName:v('emp'+n+'Supervisor'),supervisorEmail:v('emp'+n+'Email'),supervisorPhone:v('emp'+n+'Phone'),permissionToContact:c('emp'+n+'Consent')}}
function edu(n){const institution=v('edu'+n+'Institution');if(!institution)return null;return{institution,cityStateCountry:v('edu'+n+'Location'),level:v('edu'+n+'Level'),programOrMajor:v('edu'+n+'Program'),attendanceStart:v('edu'+n+'Start'),attendanceEnd:v('edu'+n+'End'),credentialEarned:v('edu'+n+'Credential'),transcriptRequested:c('edu'+n+'Transcript')}}
q('#verification-form').addEventListener('submit',async e=>{e.preventDefault();const body={applicationId:v('applicationId'),track:v('track'),applicantName:v('applicantName'),applicantEmail:v('applicantEmail'),references:[ref(1),ref(2)].filter(Boolean),employmentHistory:[emp(1),emp(2)].filter(Boolean),priorEducation:[edu(1),edu(2)].filter(Boolean),fafsa:{requested:c('fafsaRequested'),status:v('fafsaStatus'),aidYear:v('aidYear'),schoolCodeAddedAttestation:c('schoolCodeAdded'),verificationDocumentsOutstanding:c('fafsaDocs'),institutionalClearanceNote:v('fafsaNote')},transcriptConsent:c('transcriptConsent'),referenceCheckConsent:c('referenceCheckConsent'),employmentCheckConsent:c('employmentCheckConsent'),educationVerificationConsent:c('educationVerificationConsent')};const r=await fetch('/api/admissions/verification-records',{method:'POST',headers:{'content-type':'application/json','x-enrollment-admin-key':v('adminKey')},body:JSON.stringify(body)});const data=await r.json();q('#verification-result').className=r.ok?'notice success':'notice error';q('#verification-result').innerHTML='<strong>'+(r.ok?'Verification record created':'Unable to create record')+'</strong><div class="mono">'+JSON.stringify(data,null,2).replaceAll('<','&lt;')+'</div>'});
q('#background-form').addEventListener('submit',async e=>{e.preventDefault();const body={applicationId:v('bgApplicationId'),applicantName:v('bgApplicantName'),applicantEmail:v('bgApplicantEmail'),ageGroup:v('bgAgeGroup'),purpose:v('bgPurpose'),requestedLevels:['federal','state','county'].filter(x=>c('level-'+x)),requestedStates:arr(v('bgStates').toUpperCase()),requestedCounties:arr(v('bgCounties')),authorizationConsent:c('bgAuthorization'),disclosureAcknowledgment:c('bgDisclosure'),continuousAuthorizationRequested:c('bgContinuous'),typedSignature:v('bgSignature'),signedDate:v('bgSignedDate'),guardianName:v('bgGuardian'),guardianConsent:c('bgGuardianConsent'),minorLegalReviewComplete:c('bgMinorReview')};const r=await fetch('/api/admissions/background-authorizations',{method:'POST',headers:{'content-type':'application/json','x-enrollment-admin-key':v('adminKey')},body:JSON.stringify(body)});const data=await r.json();q('#background-result').className=r.ok?'notice success':'notice error';q('#background-result').innerHTML='<strong>'+(r.ok?'Authorization evidence created':'Unable to create authorization')+'</strong><div class="mono">'+JSON.stringify(data,null,2).replaceAll('<','&lt;')+'</div>'});load();
`;

app.get('/', async (_request, reply) => reply.type('text/html').send(layout('Admissions Control Center', `
<section class="panel"><h2>Institutional application & clearance package</h2><p>Use this surface after an enrollment application exists. It records pending/verified evidence without treating a check as complete until supporting evidence is actually received.</p><div id="bg-status" class="status"></div><p class="muted">FAFSA tracking here is an institutional status field only. Applicants complete the federal FAFSA through Federal Student Aid; do not enter StudentAid.gov passwords, FSA ID credentials, SSNs, tax-return details, or bank information here.</p></section>
<section class="panel"><h2>Admissions verification record</h2><div class="grid"><div class="field"><label>Enrollment admin key</label><input id="adminKey" type="password" autocomplete="off" required></div><div class="field"><label>Application ID</label><input id="applicationId" required></div><div class="field"><label>Application track</label><select id="track"><option value="prospective-student">Prospective student</option><option value="transfer-student">Transfer student</option><option value="foreign-exchange-student">Foreign exchange student</option><option value="rtpsc-new-hire-student">RTPSC new hire student</option><option value="valid-ptin-holder">Valid PTIN holder</option></select></div><div class="field"><label>Applicant full name</label><input id="applicantName" required></div><div class="field"><label>Applicant email</label><input id="applicantEmail" type="email" required></div></div><form id="verification-form">
<h3 class="section-title">Reference check</h3><div class="grid"><div class="field"><label>Reference 1 name</label><input id="ref1Name"></div><div class="field"><label>Relationship</label><input id="ref1Relationship"></div><div class="field"><label>Email</label><input id="ref1Email" type="email"></div><div class="field"><label>Phone</label><input id="ref1Phone"></div><div class="field"><label>Organization</label><input id="ref1Org"></div></div><div class="checks"><label><input id="ref1Consent" type="checkbox">Permission to contact reference 1</label></div><div class="grid"><div class="field"><label>Reference 2 name</label><input id="ref2Name"></div><div class="field"><label>Relationship</label><input id="ref2Relationship"></div><div class="field"><label>Email</label><input id="ref2Email" type="email"></div><div class="field"><label>Phone</label><input id="ref2Phone"></div><div class="field"><label>Organization</label><input id="ref2Org"></div></div><div class="checks"><label><input id="ref2Consent" type="checkbox">Permission to contact reference 2</label><label><input id="referenceCheckConsent" type="checkbox">Applicant authorizes reference verification where applicable</label></div>
<h3 class="section-title">Employment history check</h3><div class="grid"><div class="field"><label>Employer 1</label><input id="emp1Employer"></div><div class="field"><label>Role</label><input id="emp1Role"></div><div class="field"><label>Start</label><input id="emp1Start"></div><div class="field"><label>End</label><input id="emp1End"></div><div class="field"><label>Supervisor</label><input id="emp1Supervisor"></div><div class="field"><label>Supervisor email</label><input id="emp1Email" type="email"></div><div class="field"><label>Supervisor phone</label><input id="emp1Phone"></div></div><div class="checks"><label><input id="emp1Consent" type="checkbox">Permission to contact employer 1</label></div><div class="grid"><div class="field"><label>Employer 2</label><input id="emp2Employer"></div><div class="field"><label>Role</label><input id="emp2Role"></div><div class="field"><label>Start</label><input id="emp2Start"></div><div class="field"><label>End</label><input id="emp2End"></div><div class="field"><label>Supervisor</label><input id="emp2Supervisor"></div><div class="field"><label>Supervisor email</label><input id="emp2Email" type="email"></div><div class="field"><label>Supervisor phone</label><input id="emp2Phone"></div></div><div class="checks"><label><input id="emp2Consent" type="checkbox">Permission to contact employer 2</label><label><input id="employmentCheckConsent" type="checkbox">Applicant authorizes employment-history verification where applicable</label></div>
<h3 class="section-title">Prior education / transfer evaluation</h3><div class="grid"><div class="field"><label>Institution 1</label><input id="edu1Institution"></div><div class="field"><label>Location</label><input id="edu1Location"></div><div class="field"><label>Level</label><input id="edu1Level"></div><div class="field"><label>Program / major</label><input id="edu1Program"></div><div class="field"><label>Attendance start</label><input id="edu1Start"></div><div class="field"><label>Attendance end</label><input id="edu1End"></div><div class="field"><label>Credential earned</label><input id="edu1Credential"></div></div><div class="checks"><label><input id="edu1Transcript" type="checkbox">Official transcript requested</label></div><div class="grid"><div class="field"><label>Institution 2</label><input id="edu2Institution"></div><div class="field"><label>Location</label><input id="edu2Location"></div><div class="field"><label>Level</label><input id="edu2Level"></div><div class="field"><label>Program / major</label><input id="edu2Program"></div><div class="field"><label>Attendance start</label><input id="edu2Start"></div><div class="field"><label>Attendance end</label><input id="edu2End"></div><div class="field"><label>Credential earned</label><input id="edu2Credential"></div></div><div class="checks"><label><input id="edu2Transcript" type="checkbox">Official transcript requested</label><label><input id="transcriptConsent" type="checkbox">Applicant authorizes transcript request/review where permitted</label><label><input id="educationVerificationConsent" type="checkbox">Applicant authorizes prior-education verification</label></div>
<h3 class="section-title">FAFSA / financial-aid clearance status</h3><div class="grid"><div class="field"><label>Aid year</label><input id="aidYear" placeholder="2026-27"></div><div class="field"><label>Status</label><select id="fafsaStatus"><option value="not-applicable">Not applicable</option><option value="not-started">Not started</option><option value="submitted-awaiting-school">Submitted / awaiting school</option><option value="school-code-added">School code added</option><option value="verification-required">Verification required</option><option value="institutional-clearance-complete">Institutional clearance complete</option></select></div><div class="field"><label>Institutional note</label><textarea id="fafsaNote" rows="2"></textarea></div></div><div class="checks"><label><input id="fafsaRequested" type="checkbox">Applicant requests institutional financial-aid clearance tracking</label><label><input id="schoolCodeAdded" type="checkbox">Applicant attests school code was added</label><label><input id="fafsaDocs" type="checkbox">Verification documents remain outstanding</label></div><div class="actions"><button class="button" type="submit">Create admissions verification record</button></div><div id="verification-result"></div></form></section>
<section class="panel"><h2>Background screening authorization</h2><p class="danger">This creates authorization evidence only. It does not run a criminal, credit, federal, state, county, driving, or other consumer-report search.</p><form id="background-form"><div class="grid"><div class="field"><label>Application ID</label><input id="bgApplicationId" required></div><div class="field"><label>Applicant name</label><input id="bgApplicantName" required></div><div class="field"><label>Applicant email</label><input id="bgApplicantEmail" type="email" required></div><div class="field"><label>Age group</label><select id="bgAgeGroup"><option value="18-plus">18 or older</option><option value="under-18">Under 18</option></select></div><div class="field"><label>Permissible purpose</label><select id="bgPurpose"><option value="employment">Employment</option><option value="education-program-safety">Education program safety</option><option value="credentialing-review">Credentialing review</option></select></div><div class="field"><label>State / territory codes, comma separated</label><input id="bgStates" placeholder="TX, AR"></div><div class="field"><label>Counties as County, ST or FIPS, comma separated</label><textarea id="bgCounties" rows="3" placeholder="Bell County, TX; Pulaski County, AR"></textarea></div></div><div class="checks"><label><input id="level-federal" type="checkbox">Federal scope requested</label><label><input id="level-state" type="checkbox">State scope requested</label><label><input id="level-county" type="checkbox">County scope requested</label><label><input id="bgDisclosure" type="checkbox" required>I acknowledge the applicable standalone disclosure for any third-party consumer report.</label><label><input id="bgAuthorization" type="checkbox" required>I provide written authorization for the requested permissible-purpose screening subject to applicable law.</label><label><input id="bgContinuous" type="checkbox">Continuous authorization requested where lawful and clearly disclosed.</label></div><div class="grid"><div class="field"><label>Typed signature</label><input id="bgSignature" required></div><div class="field"><label>Signed date</label><input id="bgSignedDate" type="date" required></div><div class="field"><label>Guardian name if under 18</label><input id="bgGuardian"></div></div><div class="checks"><label><input id="bgGuardianConsent" type="checkbox">Guardian authorization for a minor</label><label><input id="bgMinorReview" type="checkbox">Jurisdiction-specific minor-screening legal review completed</label></div><div class="actions"><button class="button" type="submit">Create background authorization evidence</button></div><div id="background-result"></div></form></section>
<section class="panel"><h2>Seeded institutional controls</h2><pre id="seed" class="mono">Loading…</pre></section>
`, script)));

app.get('/api/health', async () => ({ ok: true, system: 'RTPU-ADMISSIONS', deployEnvironment: process.env.RTPU_DEPLOY_ENV || 'development', observedAtUtc: new Date().toISOString() }));

app.setNotFoundHandler(async (request, reply) => {
  if (request.url.startsWith('/api/')) return reply.code(404).send({ error: 'Not found' });
  return reply.code(404).type('text/html').send(layout('Not Found', '<section class="panel"><p>The requested admissions page was not found.</p></section>'));
});

const port = Number(process.env.PORT || 10000);
const host = process.env.HOST || '0.0.0.0';
await app.listen({ port, host });
