import Fastify from 'fastify';
import compress from '@fastify/compress';
import helmet from '@fastify/helmet';
import { registerEnrollmentRoutes } from './enrollment-routes';

const app = Fastify({
  logger: {
    level: process.env.LOG_LEVEL || 'info',
    redact: ['req.headers.authorization', 'req.headers.cookie', 'res.headers.set-cookie', 'req.headers.x-enrollment-admin-key']
  },
  trustProxy: true,
  bodyLimit: 1024 * 1024
});

await app.register(compress, { global: true });
await app.register(helmet, {
  global: true,
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"], baseUri: ["'self'"], formAction: ["'self'"], frameAncestors: ["'none'"],
      imgSrc: ["'self'", 'data:'], scriptSrc: ["'self'", "'unsafe-inline'"], styleSrc: ["'self'", "'unsafe-inline'"]
    }
  },
  referrerPolicy: { policy: 'strict-origin-when-cross-origin' },
  strictTransportSecurity: process.env.RTPU_DEPLOY_ENV === 'production'
    ? { maxAge: 63_072_000, includeSubDomains: true, preload: true }
    : false
});

app.addHook('onSend', async (request, reply, payload) => {
  if (request.url.startsWith('/api/')) reply.header('cache-control', 'no-store, max-age=0');
  return payload;
});

await registerEnrollmentRoutes(app);

const css = `
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111827;background:#f7f2e8}*{box-sizing:border-box}body{margin:0;background:#f7f2e8}a{color:inherit}.shell{min-height:100vh;padding:28px 16px 60px}.wrap{max-width:1120px;margin:auto}.hero{background:#0b1f3a;color:#fff;border:1px solid #c9a227;border-radius:22px;padding:28px;box-shadow:0 18px 50px rgba(11,31,58,.14)}.hero .eyebrow{color:#d4af37;text-transform:uppercase;letter-spacing:1.4px;font-size:12px;font-weight:900}.hero h1{margin:8px 0;font-size:clamp(30px,5vw,42px)}.hero p{color:#e5e7eb;line-height:1.6;max-width:920px}.nav{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.nav a{background:#fff;border:1px solid #d8d2c4;border-radius:999px;padding:9px 13px;text-decoration:none;font-weight:800;color:#0b1f3a}.panel{background:#fff;border:1px solid #d8d2c4;border-radius:18px;padding:20px;margin:18px 0;box-shadow:0 8px 22px rgba(15,23,42,.045)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.field{display:flex;flex-direction:column;gap:6px}.field label{font-size:13px;font-weight:800;color:#0b1f3a}.field input,.field select,.field textarea{font:inherit;border:1px solid #cbd5e1;border-radius:10px;padding:11px;background:#fff}.field textarea{resize:vertical}.checks{display:grid;gap:10px;margin-top:12px}.checks label{display:flex;gap:9px;align-items:flex-start;line-height:1.45}.button{appearance:none;border:0;border-radius:10px;background:#0b1f3a;color:#fff;font-weight:850;padding:12px 16px;cursor:pointer}.button.secondary{background:#fff;color:#0b1f3a;border:1px solid #0b1f3a}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.notice{padding:14px;border-radius:12px;background:#fff8df;border:1px solid #e3c565;line-height:1.5;margin:14px 0}.notice.error{background:#fff1f2;border-color:#fecdd3;color:#881337}.notice.success{background:#ecfdf5;border-color:#86efac;color:#14532d}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;word-break:break-all;background:#f8fafc;border:1px solid #e5e7eb;padding:12px;border-radius:10px}.status{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.metric{border:1px solid #d8d2c4;border-radius:14px;padding:14px;background:#fbfaf6}.metric strong{display:block;color:#0b1f3a;font-size:19px}.muted{color:#6b7280;font-size:13px}.hidden{display:none}.track{border-left:4px solid #c9a227;padding-left:14px;margin:22px 0}@media(max-width:640px){.shell{padding:16px 10px 40px}.hero{padding:22px}.panel{padding:16px}}
`;

function layout(title: string, body: string, script = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>${title}</title><style>${css}</style></head><body><main class="shell"><section class="wrap"><header class="hero"><div class="eyebrow">Ross Tax Pro University • Enrollment Services</div><h1>${title}</h1><p>Invitation, application, electronic signature, transfer/exchange review, practitioner credential intake, canonical conversion, replication and export for RTPU programs.</p></header><nav class="nav"><a href="/">Enrollment Home</a><a href="/admin/enrollment">Enrollment Administration</a></nav>${body}</section></main>${script ? `<script>${script}</script>` : ''}</body></html>`;
}

app.get('/', async (_request, reply) => reply.type('text/html').send(layout('Enrollment & Program Applications', `
<section class="panel"><h2>Application tracks</h2><div class="status"><div class="metric"><strong>Prospective</strong><span>New student</span></div><div class="metric"><strong>Transfer</strong><span>Prior school/credit review</span></div><div class="metric"><strong>Exchange</strong><span>Foreign exchange academic intake</span></div><div class="metric"><strong>RTPSC New Hire</strong><span>Employee training enrollment</span></div><div class="metric"><strong>PTIN Holder</strong><span>Practitioner diploma eligibility review</span></div></div><p class="muted">Applications start from signed invitation links issued by the RTPU enrollment office.</p></section>
<section class="panel"><h2>4-Semester Tax Practitioner Diploma</h2><p>The Tax Practitioner Diploma is configured as a four-semester institutional program. The PTIN-holder track validates PTIN format and captures applicant attestation, but PTIN validity is not represented as verified until an independent verification process confirms it.</p></section>
`)));

const adminScript = `
const q=s=>document.querySelector(s);let programs=[];
async function load(){const [r,p]=await Promise.all([fetch('/api/enrollment/readiness').then(x=>x.json()),fetch('/api/enrollment/programs').then(x=>x.json())]);programs=p.programs||[];q('#readiness').innerHTML=Object.entries(r.forms||{}).map(([k,v])=>'<div class="metric"><strong>'+(v?'READY':'NO')+'</strong><span>'+k+'</span></div>').join('');q('#readiness-note').textContent=r.note||'';refreshPrograms()}
function refreshPrograms(){const audience=q('#audience').value;const available=programs.filter(x=>(x.audiences||[]).includes(audience));q('#programId').innerHTML=available.map(x=>'<option value="'+x.id+'">'+x.title+(x.semesters?' — '+x.semesters+' semesters':'')+'</option>').join('')}
q('#audience').addEventListener('change',refreshPrograms);
q('#invite-form').addEventListener('submit',async e=>{e.preventDefault();q('#result').className='notice';q('#result').textContent='Creating invitation…';const body={audience:q('#audience').value,recipientName:q('#recipientName').value,recipientEmail:q('#recipientEmail').value,programId:q('#programId').value,expiresDays:Number(q('#expiresDays').value),inviterLabel:q('#inviterLabel').value};const res=await fetch('/api/enrollment/invites',{method:'POST',headers:{'content-type':'application/json','x-enrollment-admin-key':q('#adminKey').value},body:JSON.stringify(body)});const data=await res.json();if(!res.ok){q('#result').className='notice error';q('#result').textContent=data.error||'Invite failed';return}q('#result').className=data.delivery?.delivered?'notice success':'notice';q('#result').innerHTML='<strong>Invitation created.</strong><br>Delivery: '+String(data.delivery?.status||'not configured')+'<div class="mono">'+data.inviteUrl+'</div><div class="actions"><button class="button secondary" id="copy">Copy invite link</button><a class="button" href="'+data.inviteUrl+'" target="_blank" rel="noopener">Open application</a></div>';q('#copy').onclick=()=>navigator.clipboard.writeText(data.inviteUrl)});load();
`;

app.get('/admin/enrollment', async (_request, reply) => reply.type('text/html').send(layout('Enrollment Administration', `
<section class="panel"><h2>System readiness</h2><div id="readiness" class="status"><div class="metric"><strong>Checking</strong><span>runtime</span></div></div><p id="readiness-note" class="muted"></p></section>
<section class="panel"><h2>Send invite to enroll</h2><form id="invite-form"><div class="grid"><div class="field"><label>Enrollment admin key</label><input id="adminKey" type="password" autocomplete="off" required></div><div class="field"><label>Application track</label><select id="audience"><option value="prospective-student">Prospective student</option><option value="transfer-student">Transfer student</option><option value="foreign-exchange-student">Foreign exchange student</option><option value="rtpsc-new-hire-student">RTPSC new hire student</option><option value="valid-ptin-holder">Valid PTIN holder / practitioner</option></select></div><div class="field"><label>Recipient name</label><input id="recipientName" required></div><div class="field"><label>Recipient email</label><input id="recipientEmail" type="email" required></div><div class="field"><label>Program</label><select id="programId" required></select></div><div class="field"><label>Expires in days</label><input id="expiresDays" type="number" min="1" max="30" value="14" required></div><div class="field"><label>Inviter label</label><input id="inviterLabel" value="Ross Tax Pro University Enrollment Office"></div></div><div class="actions"><button class="button" type="submit">Create / send invite</button></div></form><div id="result"></div></section>
`, adminScript)));

const enrollScript = `
const q=s=>document.querySelector(s),params=new URLSearchParams(location.search),token=params.get('token')||'';let invite=null;
const val=id=>q('#'+id)?.value?.trim?.()||'',checked=id=>q('#'+id)?.checked===true;
function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove()}
function setTrack(a){['transfer-fields','exchange-fields','hire-fields','ptin-fields'].forEach(id=>q('#'+id).classList.add('hidden'));if(a==='transfer-student')q('#transfer-fields').classList.remove('hidden');if(a==='foreign-exchange-student')q('#exchange-fields').classList.remove('hidden');if(a==='rtpsc-new-hire-student')q('#hire-fields').classList.remove('hidden');if(a==='valid-ptin-holder')q('#ptin-fields').classList.remove('hidden')}
async function load(){const res=await fetch('/api/enrollment/invite?token='+encodeURIComponent(token));const data=await res.json();if(!res.ok){q('#load').className='notice error';q('#load').textContent=data.error||'Invalid invitation';q('#form').classList.add('hidden');return}invite=data.invite;q('#load').className='notice success';q('#load').innerHTML='<strong>Invitation verified.</strong><br>'+invite.recipientName+' • '+invite.programTitle+' • '+invite.audience.replaceAll('-',' ')+'<br><span class="muted">Expires '+invite.expiresAtUtc+'</span>';q('#email').value=invite.recipientEmail;setTrack(invite.audience)}
q('#ageGroup').addEventListener('change',()=>q('#guardian-fields').classList.toggle('hidden',q('#ageGroup').value!=='under-18'));
q('#form').addEventListener('submit',async e=>{e.preventDefault();q('#submit-result').className='notice';q('#submit-result').textContent='Signing, converting and delivering application…';const application={firstName:val('firstName'),lastName:val('lastName'),preferredName:val('preferredName'),email:val('email'),phone:val('phone'),addressLine1:val('addressLine1'),addressLine2:val('addressLine2'),city:val('city'),state:val('state'),postalCode:val('postalCode'),country:val('country'),ageGroup:val('ageGroup'),guardianName:val('guardianName'),guardianEmail:val('guardianEmail'),previousSchoolOrEmployer:val('previousSchoolOrEmployer'),educationLevel:val('educationLevel'),goals:val('goals'),accommodationsRequested:checked('accommodationsRequested'),accommodationsNotes:val('accommodationsNotes'),transferInstitution:val('transferInstitution'),transferProgram:val('transferProgram'),creditsAttempted:val('creditsAttempted'),creditsCompleted:val('creditsCompleted'),transcriptRequested:checked('transcriptRequested'),homeCountry:val('homeCountry'),homeInstitution:val('homeInstitution'),exchangeSponsor:val('exchangeSponsor'),currentVisaOrProgramStatus:val('currentVisaOrProgramStatus'),plannedStartTerm:val('plannedStartTerm'),desiredRole:val('desiredRole'),employeeOrCandidateId:val('employeeOrCandidateId'),workAuthorizationAttested:checked('workAuthorizationAttested'),ptin:val('ptin'),ptinActiveAttestation:checked('ptinActiveAttestation'),typedSignature:val('typedSignature'),electronicSignatureConsent:checked('electronicSignatureConsent'),accuracyCertification:checked('accuracyCertification'),privacyAcknowledgment:checked('privacyAcknowledgment')};const res=await fetch('/api/enrollment/applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,application})});const data=await res.json();const hasExport=!!data.exportBundle;if(hasExport){window.__bundle=data.exportBundle;window.__html=data.printableHtml}q('#submit-result').className=res.ok?'notice success':'notice error';q('#submit-result').innerHTML=(res.ok?'<strong>Application submitted to RTPU.</strong>':'<strong>Application not confirmed as submitted.</strong>')+'<br>'+String(data.error||('Application ID '+data.applicationId))+(hasExport?'<div class="actions"><button class="button secondary" id="json-download">Download signed JSON package</button><button class="button secondary" id="html-download">Download printable application</button></div>':'');if(hasExport){q('#json-download').onclick=()=>download('rtpu-application-'+data.applicationId+'.json','application/json',JSON.stringify(window.__bundle,null,2));q('#html-download').onclick=()=>download('rtpu-application-'+data.applicationId+'.html','text/html',window.__html||'')}});load();
`;

app.get('/enroll', async (_request, reply) => reply.type('text/html').send(layout('Program Enrollment Application', `
<div id="load" class="notice">Verifying invitation…</div><form id="form" class="panel"><h2>Applicant information</h2><p class="muted">Do not enter a Social Security number, bank information, passwords, passport/document numbers, or government identity-document numbers. Those records belong in separate controlled workflows.</p><div class="grid"><div class="field"><label>First name</label><input id="firstName" required></div><div class="field"><label>Last name</label><input id="lastName" required></div><div class="field"><label>Preferred name</label><input id="preferredName"></div><div class="field"><label>Email</label><input id="email" type="email" required readonly></div><div class="field"><label>Phone</label><input id="phone" required></div><div class="field"><label>Age group</label><select id="ageGroup" required><option value="">Select</option><option value="18-plus">18 or older</option><option value="under-18">Under 18</option></select></div></div><h3>Mailing address</h3><div class="grid"><div class="field"><label>Address line 1</label><input id="addressLine1" required></div><div class="field"><label>Address line 2</label><input id="addressLine2"></div><div class="field"><label>City</label><input id="city" required></div><div class="field"><label>State / region</label><input id="state" required></div><div class="field"><label>Postal code</label><input id="postalCode" required></div><div class="field"><label>Country</label><input id="country" value="United States" required></div></div><div id="guardian-fields" class="hidden track"><h3>Parent / guardian</h3><div class="grid"><div class="field"><label>Guardian name</label><input id="guardianName"></div><div class="field"><label>Guardian email</label><input id="guardianEmail" type="email"></div></div></div><h3>Background & goals</h3><div class="grid"><div class="field"><label>Previous school or employer</label><input id="previousSchoolOrEmployer"></div><div class="field"><label>Current / highest education level</label><input id="educationLevel"></div></div><div class="field"><label>Program goals</label><textarea id="goals" rows="4"></textarea></div>
<div id="transfer-fields" class="hidden track"><h3>Transfer student application</h3><div class="grid"><div class="field"><label>Transfer institution</label><input id="transferInstitution"></div><div class="field"><label>Prior program / major</label><input id="transferProgram"></div><div class="field"><label>Credits attempted</label><input id="creditsAttempted" type="number" min="0" step="0.5"></div><div class="field"><label>Credits completed</label><input id="creditsCompleted" type="number" min="0" step="0.5"></div></div><div class="checks"><label><input id="transcriptRequested" type="checkbox">I authorize RTPU to request/review an official transcript where permitted. Final transfer-credit acceptance remains pending evaluation.</label></div></div>
<div id="exchange-fields" class="hidden track"><h3>Foreign exchange student application</h3><div class="grid"><div class="field"><label>Home country</label><input id="homeCountry"></div><div class="field"><label>Home institution</label><input id="homeInstitution"></div><div class="field"><label>Exchange sponsor / organization</label><input id="exchangeSponsor"></div><div class="field"><label>Current visa or exchange-program status</label><input id="currentVisaOrProgramStatus"></div><div class="field"><label>Planned start term</label><input id="plannedStartTerm" placeholder="Fall 2026"></div></div><p class="muted">Do not enter passport, visa, SEVIS, or other document numbers here. Immigration/sponsor document review is a separate controlled process.</p></div>
<div id="hire-fields" class="hidden track"><h3>RTPSC new hire student application</h3><div class="grid"><div class="field"><label>Desired / assigned role</label><input id="desiredRole"></div><div class="field"><label>Employee or candidate ID (optional)</label><input id="employeeOrCandidateId"></div></div><div class="checks"><label><input id="workAuthorizationAttested" type="checkbox">I attest that I am authorized to work as required for the applicable role. Formal I-9 verification, W-4, payroll, background checks and employment records remain separate workflows.</label></div></div>
<div id="ptin-fields" class="hidden track"><h3>Valid PTIN holder / tax practitioner track</h3><div class="grid"><div class="field"><label>PTIN</label><input id="ptin" maxlength="9" placeholder="P12345678"></div></div><div class="checks"><label><input id="ptinActiveAttestation" type="checkbox">I attest that the PTIN entered is currently active and belongs to me.</label></div><p class="muted">The system validates PTIN format only. Status remains <strong>pending independent verification</strong> until an authorized verification source confirms validity.</p></div>
<h3>Accessibility</h3><div class="checks"><label><input id="accommodationsRequested" type="checkbox">I would like the enrollment office to contact me about an accommodation request.</label></div><div class="field"><label>Accommodation notes (optional)</label><textarea id="accommodationsNotes" rows="3"></textarea></div><h3>Electronic signature</h3><div class="field"><label>Type your full name</label><input id="typedSignature" required></div><div class="checks"><label><input id="electronicSignatureConsent" type="checkbox" required>I consent to use an electronic signature for this application.</label><label><input id="accuracyCertification" type="checkbox" required>I certify the information is accurate to the best of my knowledge.</label><label><input id="privacyAcknowledgment" type="checkbox" required>I acknowledge this information will be processed for enrollment, training, admissions/transfer review, credential review, record conversion and related institutional administration.</label></div><div class="actions"><button class="button" type="submit">Sign & submit application</button></div><div id="submit-result"></div></form>
`, enrollScript)));

app.get('/api/health', async () => ({ ok: true, system: 'RTPU-ENROLLMENT', runtime: 'fastify', deployEnvironment: process.env.RTPU_DEPLOY_ENV || 'development', observedAtUtc: new Date().toISOString() }));

app.setNotFoundHandler(async (request, reply) => {
  if (request.url.startsWith('/api/')) return reply.code(404).send({ error: 'Not found' });
  return reply.code(404).type('text/html').send(layout('Not Found', '<section class="panel"><p>The requested enrollment page was not found.</p></section>'));
});

const port = Number(process.env.PORT || 10000);
const host = process.env.HOST || '0.0.0.0';
await app.listen({ port, host });
